---
name: 'Setup MPI'
description: 'Set up a specific MPI implementation.'

runs:
  using: 'composite'
  steps:
    - id: setup-mpi
      run: ${GITHUB_ACTION_PATH}/setup-mpi.sh
      shell: bash
    - id: setup-doxygen
      run: ${GITHUB_ACTION_PATH}/setup-doxygen.sh
      shell: bash
