version = 1
SPDX-PackageName = "ci-actions"
SPDX-PackageSupplier = "Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-PackageDownloadLocation = "https://root-sim.github.io/"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2021 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2021 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2021 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2021 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "GPL-3.0-only"
