---
name: 'Update Copyright'
description: 'Updates copyright notice and creates a pull request. Meant to be run in a cron job at the beginning of the year.'
inputs:
  branch-to-update:
    description: Specify the branch where the copyright notice should be updated
    default: develop
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-to-update }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - id: update-copyright
      run: python ${GITHUB_ACTION_PATH}/update_copyright.py
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update copyright year |
          
          Happy New Year! °🥂⋆.ೃ🍾࿔*:･
        title: Update copyright year
        body: Happy New Year! °🥂⋆.ೃ🍾࿔*:･
        branch: update-copyright-action
        base: ${{ inputs.branch-to-update }}
        branch-suffix: short-commit-hash
