---
name: 'REUSE check'
description: 'Fail if the project is not REUSE compliant'

runs:
  using: 'composite'
  steps:
    - id: reuse-check
      run: ${GITHUB_ACTION_PATH}/reuse-check.sh
      shell: bash
