---
name: 'Documentation Coverage'
description: 'Compute Documentation Coverage'
inputs:
  accept-threshold:
    description: The coverage threshold that makes the check pass
    default: "60"
    required: false

runs:
  using: 'composite'
  steps:
    - id: documentation-coverage
      run: ${GITHUB_ACTION_PATH}/doc-coverage.sh
      shell: bash
      if: ${{ github.event_name == 'pull_request' }}
      env:
        INPUT_THRESHOLD: ${{ inputs.accept-threshold }}
