---
name: 'Documentation Coverage'
description: 'Compute Documentation Coverage'
inputs:
  accept-threshold:
    description: The coverage threshold that makes the check pass
    default: "60"
    required: false
  build-path:
    description: The path where CMake has generated the docs
    default: build
    required: false

runs:
  using: 'composite'
  steps:
    - id: documentation-coverage
      run: ${GITHUB_ACTION_PATH}/doc-coverage.sh
      shell: bash
      env:
        INPUT_THRESHOLD: ${{ inputs.accept-threshold }}
        INPUT_BUILD_PATH: ${{ inputs.build-path }}
        EVENT: ${{ github.event_name }}
