---
name: 'Generate Documentation'
description: 'Generate Documentation'
inputs:
  docs-target:
    description: The CMake target used to generate the docs
    default: doc
    required: false

runs:
  using: 'composite'
  steps:
    - id: documentation-coverage
      run: ${GITHUB_ACTION_PATH}/generate-docs.sh
      shell: bash
      env:
        TARGET: ${{ inputs.docs-target }}
