---
name: 'Generate Documentation'
description: 'Generate Documentation'

runs:
  using: 'composite'
  steps:
    - id: documentation-coverage
      run: ${GITHUB_ACTION_PATH}/generate-docs.sh
      shell: bash
