name: optional-init

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: REUSE check
      uses: ./reuse-check
    - name: Initialize Environment
      uses: ./init
      with:
        with-mpi: no
        with-doxygen: no
    - name: Verify initialization
      run: |
        exists()
        {
          command -v "$1" >/dev/null 2>&1
        }
        if exists mpicc; then
          exit 1
        fi
        if exists doxygen; then
          exit 1
        fi
