name: update-copyright

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update copyright
      uses: ./update-copyright
